### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by fifthguy** [beast-dev/RBeast#14]
Hi,

i seem to be unable to install RBeast due to a dependency issue, it seems to be unable to find beastier & beautier (eventhough they are out there...)

I also cant install them separately, due to the same problem. (some of the output below the "=====")

Can you help?

Thank you, T

==================================================

ERROR: dependency ‘beastier’ is not available for package ‘beautier’
ERROR: dependency ‘beautier’ is not available for package ‘beastier’
ERROR: dependency ‘beastier’ is not available for package ‘RBeast’

**Comment by richelbilderbeek** [comment]
Working on it. 

I see that RBeast does not have a problem, nor does [beautier](https://github.com/richelbilderbeek/beautier).I estimate that problem is a cyclic dependency in [beastier](https://github.com/richelbilderbeek/beastier.

**Comment by richelbilderbeek** [comment]
I think this is fixed, as:

 * both [beautier](https://github.com/richelbilderbeek/beautier) and [beastier](https://github.com/richelbilderbeek/beastier) can be installed without depending on each other
 * they both build successfully
 * I cannot get RBeast to fail building

If your problem is not fixed yet, please re-open this Issue.

**Comment by fifthguy** [comment]
Hi!

Yes, now it installs!

Thank you very much!

Best, T

**Comment by richelbilderbeek** [comment]
I always make time for users! Thanks for using (an unknown subset of) RBeast!
